### ISSUE TITLE
Dots are incomplete with certain margins.

### ISSUE THREAD

**Issue by rafaelpap** [mcnees/LaTeX-Graph-Paper#15]
If I use
\usepackage[pattern=dot, colorset=std, textarea, geometry={a4paper, margin=1in}]{gridpapers}
the top, bottom and left dots are cutted.
It's the intended behaviour?

Thanks,
Rafael RP
[dots.pdf](https://github.com/mcnees/LaTeX-Graph-Paper/files/6175234/dots.pdf)

**Comment by mcnees** [comment]
With those margins and the default grid size the pattern will fall right on the edge of the text area, showing only half of the outermost dots. In an upcoming version we’ll have the option of expanding or contracting the margins so that a whole number of dots fit. Until then, changing the margins to 0.95in fixes the problem.

**Comment by rafaelpap** [comment]
Ok, thanks for the quick answer.
