### ISSUE TITLE
Newbie having trouble with instructions

### ISSUE THREAD

**Issue by pfuntner** [mcnees/LaTeX-Graph-Paper#26]
I saw your post on Mastodon and wanted to try out the repo.  I'm a software engineer (mostly Python and Ansible these days) but don't think I've ever used Latex.

I tried the instructions but I think something isn't working right.  I was confused by _simply run latex twice on the file "graph paper.tex" to produce a pdf. From the command line, type: `pdflatex "graph paper.tex"`_... I'm not sure why I need to run a command twice or what command is that I'm supposed to run twice but I tried the suggested command once:

```
$ pdflatex "graph paper.tex"
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./graph paper.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-01-21>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo)) (./gridpapers.sty

! LaTeX Error: File `xkeyval.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
(/usr/share/texlive/texmf-dist/tex/latex/kvoptions/kvoptions.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)
(/usr/share/texlive/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty))

! LaTeX Error: File `xcolor.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 

! LaTeX Error: File `tikz.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Undefined control sequence.
<recently read> \usetikzlibrary 
                                
l.30 \usetikzlibrary
                    {patterns.meta,calc}
?     
! Emergency stop.
<recently read> \usetikzlibrary 
                                
l.30 \usetikzlibrary
                    {patterns.meta,calc}
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on "graph paper.log".
$ ls -lt
total 80
-rw-rw-r-- 1 mrbruno mrbruno  2687 May 20 09:12 'graph paper.log'
-rw-rw-r-- 1 mrbruno mrbruno 28222 May 20 09:10  gridpapers.dtx
-rw-rw-r-- 1 mrbruno mrbruno  2409 May 20 09:10  gridpapers.ins
-rw-rw-r-- 1 mrbruno mrbruno 19513 May 20 09:10  gridpapers.sty
drwxrwxr-x 2 mrbruno mrbruno  4096 May 20 09:10  examples
drwxrwxr-x 3 mrbruno mrbruno  4096 May 20 09:10  for-CTAN
-rw-rw-r-- 1 mrbruno mrbruno   119 May 20 09:10 'graph paper.tex'
-rw-rw-r-- 1 mrbruno mrbruno  1114 May 20 09:10  LICENSE
-rw-rw-r-- 1 mrbruno mrbruno  4493 May 20 09:10  README.md
$
```

I was just hitting Enter to the prompts and obviously I don't know what I'm doing.  I don't think the log file is significantly different than stdout but here is it: [graph paper.log](https://github.com/mcnees/LaTeX-Graph-Paper/files/11522436/graph.paper.log)

**Comment by mcnees** [comment]
Hi John,

It looks like PGF / TikZ isn’t installed. This is a library (“package”) for LaTeX that gives it a set of commands for drawing various graphic primitives.

What LaTeX distro are you using? Most distros have facilities for one-click installing packages, so it should be as simple as using that to install TikZ.

Let me know if that works, and if not then I will do what I can to help.

Best,
Bob



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: John Pfuntner ***@***.***>
Sent: Saturday, May 20, 2023 8:24:29 AM
To: mcnees/LaTeX-Graph-Paper ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mcnees/LaTeX-Graph-Paper] Newbie having trouble with instructions (Issue #26)


I saw your post on Mastodon and wanted to try out the repo. I'm a software engineer (mostly Python and Ansible these days) but don't think I've ever used Latex.

I tried the instructions but I think something isn't working right. I was confused by simply run latex twice on the file "graph paper.tex" to produce a pdf. From the command line, type: pdflatex "graph paper.tex"... I'm not sure why I need to run a command twice or what command is that I'm supposed to run twice but I tried the suggested command once:

$ pdflatex "graph paper.tex"
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./graph paper.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-01-21>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo)) (./gridpapers.sty

! LaTeX Error: File `xkeyval.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:
(/usr/share/texlive/texmf-dist/tex/latex/kvoptions/kvoptions.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)
(/usr/share/texlive/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty))

! LaTeX Error: File `xcolor.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:

! LaTeX Error: File `tikz.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:
! Undefined control sequence.
<recently read> \usetikzlibrary

l.30 \usetikzlibrary
                    {patterns.meta,calc}
?
! Emergency stop.
<recently read> \usetikzlibrary

l.30 \usetikzlibrary
                    {patterns.meta,calc}
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on "graph paper.log".
$ ls -lt
total 80
-rw-rw-r-- 1 mrbruno mrbruno  2687 May 20 09:12 'graph paper.log'
-rw-rw-r-- 1 mrbruno mrbruno 28222 May 20 09:10  gridpapers.dtx
-rw-rw-r-- 1 mrbruno mrbruno  2409 May 20 09:10  gridpapers.ins
-rw-rw-r-- 1 mrbruno mrbruno 19513 May 20 09:10  gridpapers.sty
drwxrwxr-x 2 mrbruno mrbruno  4096 May 20 09:10  examples
drwxrwxr-x 3 mrbruno mrbruno  4096 May 20 09:10  for-CTAN
-rw-rw-r-- 1 mrbruno mrbruno   119 May 20 09:10 'graph paper.tex'
-rw-rw-r-- 1 mrbruno mrbruno  1114 May 20 09:10  LICENSE
-rw-rw-r-- 1 mrbruno mrbruno  4493 May 20 09:10  README.md
$


I was just hitting Enter to the prompts and obviously I don't know what I'm doing. I don't think the log file is significantly different than stdout but here is it: graph paper.log<https://github.com/mcnees/LaTeX-Graph-Paper/files/11522436/graph.paper.log>

**Comment by pfuntner** [comment]
Thanks for your fast reply!

> What LaTeX distro are you using?

Ummm...  I dunno?

```
$ apt list --installed | grep -i latex

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

preview-latex-style/jammy,jammy,now 12.2-1ubuntu1 all [installed,automatic]
texlive-latex-base/jammy,jammy,now 2021.20220204-1 all [installed]
texlive-latex-recommended/jammy,jammy,now 2021.20220204-1 all [installed,automatic]
$ pdflatex  --version
pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian)
kpathsea version 6.3.4/dev
Copyright 2021 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.03
$
```

I installed `libpgf6` and `tikzit` with `apt` and think they helped some but I'm still getting an error:

```
$ pdflatex "graph paper.tex"
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./graph paper.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-01-21>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo)) (./gridpapers.sty
(/usr/share/texlive/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkvutils.tex
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/keyval.tex))))
(/usr/share/texlive/texmf-dist/tex/latex/kvoptions/kvoptions.sty
(/usr/share/texlive/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)
(/usr/share/texlive/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty))
(/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/frontendlayer/tikz.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/basiclayer/pgf.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfrcs.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-common.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-common-lists.t
ex)) (/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-latex.def
) (/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfrcs.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/pgf.revision.tex)))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/basiclayer/pgfcore.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/systemlayer/pgfsys.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeysfiltered.code.t
ex)) (/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgf.cfg)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-pdftex.def
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-common-pdf.de
f)))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsyssoftpath.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsysprotocol.code.
tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcore.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathcalc.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathutil.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathparser.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.basic.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.trigonomet
ric.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.random.cod
e.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.comparison
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.base.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.round.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.misc.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.integerari
thmetics.code.tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfloat.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfint.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepoints.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathconstruct.
code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathusage.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorescopes.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoregraphicstate.c
ode.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransformation
s.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorequick.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreobjects.code.t
ex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathprocessing
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorearrows.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreshade.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreimage.code.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreexternal.code.
tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorelayers.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransparency.c
ode.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepatterns.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorerdf.code.tex))
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduleshapes.code.tex
) (/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduleplot.code.tex
)
(/usr/share/texlive/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-0-65
.sty)
(/usr/share/texlive/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-1-18
.sty)) (/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgffor.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/math/pgfmath.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgffor.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryplothandlers
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmodulematrix.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarytopaths.code.tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarypatterns.meta.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibrarypatterns.met
a.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarycalc.code.tex)
(/usr/share/texlive/texmf-dist/tex/latex/tikzpagenodes/tikzpagenodes.sty

! LaTeX Error: File `ifoddpage.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: <Ctrl-D>
$
```

Here's the log: [graph paper.log](https://github.com/mcnees/LaTeX-Graph-Paper/files/11522587/graph.paper.log)

**Comment by mcnees** [comment]
Hmm, it has been several years since I’ve install TeX on a linux distro, and back then it was Red Hat / Fedora, but I bet we can work this out.

Can you tell me if you have texlive installed? It should show up in the same installed list via apt.

Best,
Bob

From: John Pfuntner ***@***.***>
Date: Saturday, May 20, 2023 at 9:53 AM
To: mcnees/LaTeX-Graph-Paper ***@***.***>
Cc: Mcnees, Robert ***@***.***>, Comment ***@***.***>
Subject: Re: [mcnees/LaTeX-Graph-Paper] Newbie having trouble with instructions (Issue #26)

Thanks for your fast reply!

What LaTeX distro are you using?

Ummm... I dunno?

$ apt list --installed | grep -i latex



WARNING: apt does not have a stable CLI interface. Use with caution in scripts.



preview-latex-style/jammy,jammy,now 12.2-1ubuntu1 all [installed,automatic]

texlive-latex-base/jammy,jammy,now 2021.20220204-1 all [installed]

texlive-latex-recommended/jammy,jammy,now 2021.20220204-1 all [installed,automatic]

$

I installed libpgf6 and tikzit with apt and think they helped some but I'm still getting an error:

$ pdflatex "graph paper.tex"

This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=pdflatex)

 restricted \write18 enabled.

entering extended mode

(./graph paper.tex

LaTeX2e <2021-11-15> patch level 1

L3 programming layer <2022-01-21>

(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls

Document Class: article 2021/10/04 v1.4n Standard LaTeX document class

(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo)) (./gridpapers.sty

(/usr/share/texlive/texmf-dist/tex/latex/xkeyval/xkeyval.sty

(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkeyval.tex

(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkvutils.tex

(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/keyval.tex))))

(/usr/share/texlive/texmf-dist/tex/latex/kvoptions/kvoptions.sty

(/usr/share/texlive/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)

(/usr/share/texlive/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty))

(/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty

(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)

(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def))

(/usr/share/texlive/texmf-dist/tex/latex/pgf/frontendlayer/tikz.sty

(/usr/share/texlive/texmf-dist/tex/latex/pgf/basiclayer/pgf.sty

(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfrcs.sty

(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-common.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-common-lists.t

ex)) (/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-latex.def

) (/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfrcs.code.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/pgf.revision.tex)))

(/usr/share/texlive/texmf-dist/tex/latex/pgf/basiclayer/pgfcore.sty

(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty

(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty

(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)

(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)))

(/usr/share/texlive/texmf-dist/tex/latex/pgf/systemlayer/pgfsys.sty

(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys.code.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeysfiltered.code.t

ex)) (/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgf.cfg)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-pdftex.def

(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-common-pdf.de

f)))

(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsyssoftpath.code.

tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsysprotocol.code.

tex))

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcore.code.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathcalc.code.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathutil.code.tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathparser.code.tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.code.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.basic.code

.tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.trigonomet

ric.code.tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.random.cod

e.tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.comparison

.code.tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.base.code.

tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.round.code

.tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.misc.code.

tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.integerari

thmetics.code.tex)))

(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfloat.code.tex))

(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfint.code.tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepoints.code.te

x)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathconstruct.

code.tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathusage.code

.tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorescopes.code.te

x)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoregraphicstate.c

ode.tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransformation

s.code.tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorequick.code.tex

)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreobjects.code.t

ex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathprocessing

.code.tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorearrows.code.te

x)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreshade.code.tex

)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreimage.code.tex



(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreexternal.code.

tex))

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorelayers.code.te

x)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransparency.c

ode.tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepatterns.code.

tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorerdf.code.tex))

)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduleshapes.code.tex

) (/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduleplot.code.tex

)

(/usr/share/texlive/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-0-65

.sty)

(/usr/share/texlive/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-1-18

.sty)) (/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgffor.sty

(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty

(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex))

(/usr/share/texlive/texmf-dist/tex/latex/pgf/math/pgfmath.sty

(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex))

(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgffor.code.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex)))

(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex



(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryplothandlers

.code.tex)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmodulematrix.code.tex

)

(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik

zlibrarytopaths.code.tex)))

(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik

zlibrarypatterns.meta.code.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibrarypatterns.met

a.code.tex))

(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik

zlibrarycalc.code.tex)

(/usr/share/texlive/texmf-dist/tex/latex/tikzpagenodes/tikzpagenodes.sty



! LaTeX Error: File `ifoddpage.sty' not found.



Type X to quit or <RETURN> to proceed,

or enter new name. (Default extension: sty)



Enter file name: <Ctrl-D>

$

Here's the log: graph paper.log<https://github.com/mcnees/LaTeX-Graph-Paper/files/11522587/graph.paper.log>

**Comment by duetosymmetry** [comment]
I believe the apt package you want is called `texlive-latex-extra`. It should have all the dependancies, and the `gridpapers` package should also be included (I found a contents listing at https://packages.debian.org/sid/texlive-latex-extra). Once you have `texlive-latex-extra` installed, you should be able to compile examples like `graph paper.tex` without needing to have `gridpapers.sty` in the same working directory.

**Comment by duetosymmetry** [comment]
Sounds like this was completed, since there was no follow-up. Closing
